### ISSUE TITLE
Avoid releasing on documentation only changes

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1046]
**Author the user story for this feature**

As a Flank developer, I want to only release snapshots when the code changes so I can save CI compute resources.

**Is your feature request related to a problem? Please describe.**

Merging a pull request that only ever changes readme.md will produce a new flank snapshot. Let's modify the release pipeline to only perform releases on code changes. As Flank is becoming more of a monorepo, we can add intelligence to CI so that builds only happen when they make sense.

**Comment by Sloox** [comment]
After a little bit of research I can see mainly two ways to approach it. But instead of simply just submitting code i would prefer to get some opinions first.

1. We could introduce a conditional step into the release.yml code and bail out the release process. By leveraging our pull request titles it could be something simple such as:
```
- name: Check if should release
      run: |
        pattern="(?:\b|')(feat|fix|refactor|perf)(?:\b|')[:]\s"
        title=$(git log --pretty=format:"%s" --abbrev-commit -1)
        if [[ $title =~ $pattern ]]; then 
          echo Not releasing on no code change
          exit 1
        fi;
```
2. We could write a custom action that scans through the files and actually checks if the files modified are of extension kt or .doc or anything else and skip the release process.

Is there any other solution that I may have missed?

@piotradamczyk5 you are the most familiar with this process. what do you think?

**Comment by bootstraponline** [comment]
If you look at Bitrise (create an account, use selective builds), they have a glob pattern that defines when builds can be triggered. I think we could build something similar using a GitHub action.

For example, only build if changes are in `test_runner/**

**Comment by piotradamczyk5** [comment]
@Sloox you could filter file paths . Please read how to do it in https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

We have some filtering for flank scripts

**Comment by bootstraponline** [comment]
> Also, I think that we should only filter documentation changes for `snapshot`. Am I right @bootstraponline ?

agreed

**Comment by Sloox** [comment]
Thanks will look and get back to you.
