### ISSUE TITLE
Review and unify detekt settings

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1146]
Detekt seems to be missing some settings. Some problems were spotted like unused imports, exceeded line lenght.
Configuration should be review.

As an addition to this issue we can unify detekt configuration for all submodules

**Comment by Sloox** [comment]
@pawelpasterz there was this ticket done on detekt settings https://github.com/Flank/flank/pull/1000/files && https://github.com/Flank/flank/pull/1039
Some of the settings you mention like line length are disabled on purpose as they cause a huge amount of issues when interacting with the ide. We already had a discussion about it as far as I remember with @jan-gogo that a combination of the current detekt settings and the IDE we use should be enough to cover all the bases.
i.e. Detekt settings + common IDE settings

There could however be some issues where the detekt is a little bit buggy due to the global gradle changes. I thought I would inform you just so there is some reference here.

**Comment by Sloox** [comment]
Detekt is also auto applying the changes. Ofcourse detekt wont make changes to the actual code when its run in workflows so it wont pick those issues up.
For example as far as I am aware a case where it could happen is as follows:
`./gradlew clean build` is called.
detekt is run and it auto-fixes the issues locally.
This auto-fix will not come up as an error.
But the auto-fix is not applied to the project source as that would require a commit and a pull request and this is only happening in the github workflows.

I think this may be the issue that is occurring where the errors are not being picked up.

**Comment by piotradamczyk5** [comment]
After a discussion with @Sloox we decided:
- adjust the configuration for Detekt and submodules
- push changes made during CI workflow
