### ISSUE TITLE
When smart sharding is used, some tests are not executed.

### ISSUE THREAD

**Issue by dbarwacz** [Flank/flank#1569]
I attempted to upgrade our setup to use smart sharding recently. 

Configuration seemed to work flawlessly, but I realised some of tests are not executed at all. 

1. Let's assume you have test suite with ~270 tests. 
2. android_shards.json have 20 shards, with around 13-14 tests each. 
3. JUnitReport.xml does have record of 20 test suites (`<testsuite>` tag in xml).
4. Interestingly, some of them are empty, ie instead of expected 
```
<testsuite name="Pixel2-29-en-portrait" tests="****14****" failures="13" flakes="0" errors="0" skipped="0" time="239.862" timestamp="2021-02-05T13:26:39" hostname="localhost">
``` 
we get:
```
<testsuite name="Pixel2-29-en-portrait" tests="****0****" failures="0" flakes="0" errors="0" skipped="0" time="0.000" timestamp="1970-01-01T00:00:00" hostname="localhost"/>
``` 
(emphasis on numbers mine, also notice timestamp - does it mean the emulator failed to start?). 
5. `{device}-test-results-merged.xml` do not seem to even be aware of missing tests. 
6. There is a logcat for 'failed' device available (test-lab-4nv5xxtjty0h6-isys7vj9jhnm2/2021-02-05_14-22-22.503000_rt8k/matrix_0/Pixel2-29-en-portrait-shard_2/logcat)
7. As a result, some tests are not run; this in turns means that feature is not reliable to use. 

I guess that it could mean that FTL is at fault here. Would be good to get a validation from you first if possible. 
If anything, I think it would be superb if flank could recognise that FTL is misbehaving (for example by verifying the number of tests expected to run + actual results) 

While I tried to better understand the issue I found out: 
Other issues mentioned @Ignore could be causing similar problems (but not enough tests ignored to explain that), 
testTargets do not explain that either (not enough `notAnnotation` used)
I also updated relevant libraries: 
* flank: 21.02.0
* androidx.test:orchestrator:1.3.0
* androidx.test:core:1.3.0
* androidx.test.ext:junit:1.1.2
* androidx.test:runner:1.3.0
* androidx.test:rules:1.3.0
* androidx.test.ext:truth:1.3.0
* androidx.test.espresso:espresso-core:3.3.0
* androidx.test.espresso:espresso-contrib:3.3.0
* androidx.test.espresso:espresso-intents:3.3.0
* androidx.test.espresso:espresso-web:3.3.0
* com.google.truth:truth:1.0

It also seems that number of failing shards is decreasing over time. Initially, 1/2 of tests were 'disappeared', now it's ~ 1/4. 

Example run if we need to look into detains on google's side: https://console.cloud.google.com/storage/browser/test-lab-4nv5xxtjty0h6-isys7vj9jhnm2/2021-02-05_14-22-22.503000_rt8k

**Comment by xzer000** [comment]
The problem is with emulators on firebase - https://firebase-community.slack.com/archives/C1MTSQ5QT/p1612795027192500
`Hi :), since 02/04/2021 (I checked the logs from the last two weeks and the first such failures happened on February 4) I started to observe the increased amount of app crashes (app crashes and no tests are run, example failures: matrix-j2u522ezb1cga - fragment 1 or matrix-1z3a6u7wimjx3 - fragment 17). It looks like a problem with the webview - we are crashing app because of the update and restart of webview on the emulator
02-08 02:17:28.382: I/ActivityManager(1514): Force stopping com.google.android.webview appid=10099 user=0: pkg removed
02-08 02:17:28.383: I/ActivityManager(1514): Killing 8952:com.azimo.sendmoney.debug1/u0a133 (adj 0): stop com.google.android.webview
02-08 02:17:28.390: I/cr_ChildProcessService(9323): Destroying ChildProcessService pid=9323
02-08 02:17:28.391: W/ActivityManager(1514): Crash of app com.azimo.sendmoney.debug1 running instrumentation ComponentInfo{com.azimo.sendmoney.debug1.test/com.azimo.sendmoney.instrumentation.config.AzimoTestRunner}
02-08 02:17:28.391: I/ActivityManager(1514): Force stopping com.azimo.sendmoney.debug1 appid=10133 user=0: finished inst
02-08 02:17:28.393: I/ActivityManager(1514): Killing 9301:com.google.android.webview:webview_service/u0a99 (adj 0): stop com.azimo.sendmoney.debug1
02-08 02:17:28.394: I/ActivityManager(1514): Killing 9323:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a133i0 (adj 0): isolated not needed02-08 02:17:28.394: I/ActivityManager(1514): Killing 9323:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a133i0 (adj 0): isolated not needed`

**Comment by bootstraponline** [comment]
> I think it would be superb if flank could recognise that FTL is misbehaving (for example by verifying the number of tests expected to run + actual results)

I like this idea, I think it may be difficult with parameterized tests though. Flank may not know exactly how many tests are expected to run. We can look into it.

This issue seems like a problem in test lab itself, where they're failing to run all the tests due to infrastructure instability.

**Comment by dbarwacz** [comment]
I see, in that case should I'll create a new one issue with those specific change request and close this, as my report is incorrect - the problem was caused when FTL has introduced a change externally when device images were updated, irrespective of my changes related to smart sharding.
