### ISSUE TITLE
@Ignored Tests being counted as passed during the extraction of the report.xml file

### ISSUE THREAD

**Issue by shawnshaligram** [Flank/flank#1603]
**Describe the bug**
We have a few test classes which are being annotated by @Ignore. After upgrading from v4 to v21 of Flank Test Runner we observed the test which are ignored are still counted as passed in the report.xml. The correct number is shown when running on firebase tho just not during the post-run/reporting phase.

**To Reproduce**
1. Create two tests 
2. Skip one of them like this     
    @Ignore
    @Throws(IOException::class)
    
3. Run on Firebase and check CI job for details 

**Expected behavior**
Skip tests shouldn't count as passed in the report.xml file

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?

Yes

> Post the output of ` flank --version`.

v21

**Additional context**
> Add any other context about the problem here.

**Comment by pawelpasterz** [comment]
> We have a few test classes which are being annotated by @ignore.

Flank does not support `@Ignore` on the class level, please check if that might cause inconsistency in your results.

I am unable to reproduce the behavior you have, I might be missing some info:
* do you get the same result when running with `gcloud` instead of flank?
* is it `Ignore` annotation from JUnit or another tool?
* could you share your config?

Please note, flank does not send ignored test to the test lab and that is desired behaviour

**Comment by jan-gogo** [comment]
This issue needs some more investigation.

**Comment by jan-gogo** [comment]
I am closing the issue due to we cannot reproduce the bug and no response for 2 weeks.
