### ISSUE TITLE
Print run duration

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#1666]
It would be great if Flank prints the duration of the entire execution at the end. The intermediate steps duration breakdown is really great! But it would be really nice if, at the end of _everything_, Flank could print the combined duration.

**Comment by Sloox** [comment]
We potentially see 3 different possible runs to print and they can be explained as follows:
1. Entire execution of the Flank run where it is timed from the start of Flank Execution and until it shuts down.
2. Entire execution of the interaction with Google Firebase CLI, i.e. The time from when the tests execute till when they shutdown.
3. Total cost duration, a flank estimate of the time that is billed for (Ultimately the correct source of truth will be the final billing cost)

1. Can be calculated by simply summing up the intemediatry steps.
2. Might need some work to seperate out where exactly the CLI is interacted with
3. Is a tricky one and needs to be discussed if we should approach it (Due to possibility of being incorrect and legal issues)

@jan-gogo WDYT?
