### ISSUE TITLE
Investigate work required for merging Fladle

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1681]
Prepare a document containing a list of actions required for merging Fladle into Flank monorepo.
Describe each action briefly if needed. 
Attach document as a comment.

This list is important for further work in the scope of epic.

**Comment by piotradamczyk5** [comment]
# Steps to merge Fladle


## IDEA 1: Merge Fladle and Flank repositories

### Get latest Fladle version

From [Fladle repository](https://github.com/runningcode/fladle) take module `fladle-plugin` and move it into [Flank repository](https://github.com/Flank/flank)

### Update dependencies

For know dependencies replace its name and version with coresponding names and version from `buildSrc` durectory. For new dependencies 

### Think about naming

If we would like to change plugin name, please update all `fladle` occurence with new name

### Add test project

Add test flank project and use it as our test tool for fladle changes. The test project could be taken from  [Fladle repository](https://github.com/runningcode/fladle) or written from scratch.

### Remove Flank dependencies

Replace all flank external dependencies with flank `test_runner` module

### Setup new publications

Setup new plugin publication with credentials managed by Flank team

### Move Fladle documentation

Move documentation from fladle repo and place it as subheader in Flank documentation

## IDEA 2: Use composite builds

Based on @bootstraponline and @no [input](https://gogoapps.slack.com/archives/GU4SZEP0S/p1617721313003700?thread_ts=1617707697.001400&cid=GU4SZEP0S)
instead of merging Fladle and Flank repositories together we could achive same behaviour using [Gradle composite builds](https://docs.gradle.org/current/userguide/composite_builds.html)



<TODO>

**Comment by pawelpasterz** [comment]
What are (if there are any) the pros and cons of each idea?

**Comment by runningcode** [comment]
My proposal would be the following:

1. Add an integration test for the fladle plugin in the flank project. This is a good idea whether or not we are going to integrate both projects to prevent regressions.
2. Use a composite build to substitute the flank dependency for the in development version in this integration test.

**Comment by piotradamczyk5** [comment]
Thank you @runningcode for your input. You have the biggest knowledge about Fladle, so I think that we should follow your proposition

@jan-gogo could we treat steps proposed by @runningcode as the next tasks in this epic?

**Comment by runningcode** [comment]
Here are some example integration tests: https://github.com/runningcode/fladle/blob/master/fladle-plugin/src/test/java/com/osacky/flank/gradle/integration/FlankGradlePluginIntegrationTest.kt

**Comment by jan-gogo** [comment]
IDEA 2 sounds reasonable since we have a lot of work around Corellium and refactor. Fladle integration test will protect us from losing compatibility with small effort. I will vote for leaving IDEA 1 for the future, now we should focus only on IDEA 2.

**Comment by piotradamczyk5** [comment]
Investigation done, follow up ticket created https://github.com/Flank/flank/issues/1804
