### ISSUE TITLE
Filtering Sentry errors

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#1958]
**Author the user story for this feature**

As a Flank developer, I want to be notified **only** about critical Flank errors (Sentry events).

**Describe the solution**

- find out which events we should track with Sentry (documentation)
- find out how to label major and ignore minor critical issues
- investigate slack / zenhub integrations (notifications/issue creation) for critical sentry events

**Comment by adamfilipow92** [comment]
https://sentry.io/integrations/slack/
https://sentry.io/integrations/github/
https://sentry.io/integrations/

**Comment by piotradamczyk5** [comment]
# Events for tracking
- ALL Google Api issues -> level `DEBUG`
- other issues -> level `ERROR`

then all errors with level `ERROR` will be treated as critical

Also, integration tests should have some special label

# integration
We should set up Sentry > Slack integration which will post messages to a separate channel or existing one. We need @bootstraponline help because he is the owner of the Sentry flank project

**Comment by bootstraponline** [comment]
@piotradamczyk5 You're a sentry owner now 🙂
