### ISSUE TITLE
Logging framework for Flank

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#446]
Use what ktor is using for logging. Add `--debug` flag and `debug: true` option in flank yaml.

- SLF4J - https://www.slf4j.org/
- https://ktor.io/servers/logging.html

print detected macOS version in `FtlConstants.kt`

> val macOS: Boolean = (System.getProperty("os.name") ?: "").toLowerCase().indexOf("mac") >= 0
    
if a mac is detected as linux then sharding may fail (if the bundled nm binary isn't up to date).

**Comment by valeraz** [comment]
This lib on top of slf4j seems to be pretty popular: https://github.com/MicroUtils/kotlin-logging

**Comment by bootstraponline** [comment]
https://github.com/google/flogger

**Comment by jan-gogo** [comment]
Hi @bootstraponline , I need some clarifications if debug option should work for any command or only for `android run` and `ios run`. I am asking because the first option sound much more reasonable, but it also brings much more changes in implementation. 
For example, if debug flag should work for all commands and can be passed from cli and also from config file, it requires to handle configuration file in `Main` instead of `AndroidRunCommand` and `AndroidRunCommand`. It will also change order of cli args `--config` flag will be first before any other command.
The simplest solution to achieve first option without doing any changes with handling configuration files, can be allowing debug flag only by cli. Correct me if I am wrong.

**Comment by bootstraponline** [comment]
I think allowing debug flag only by CLI is fine. I like going with the simplest possible solution first. We can always add complexity later if it's truly necessary.
