### ISSUE TITLE
Create results-dir

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#781]
Bug reported via Slack.

- Flank should create results-dir if it doesn't exist
- Let's add a test to verify Flank creates results-dir when the dir doesn't exist

> pavelnazimok
>
> Have this in config:
> 
> ```  
> results-bucket: sdk_test_results
>   results-dir: test_results-6282-2020-05-13_10:34:59
> ```
>
> 
> But Flank gives me this error:
> `'test_results-6282-2020-05-13_10:34:59' from results-dir doesn't exist`
> Using last release
> The same config worked without error on pre v20 snapshot

**Comment by pawelpasterz** [comment]
@bootstraponline 
cc @adamfilipow92 
> * Let's add a test to verify Flank creates results-dir when the dir doesn't exist

I don't think if this is something we can check easily (at least if we talk about unit tests). `results-dir` is a name for directory on gcs bucket. So to verify it we would need to connect to gcs and verify bucket which is, for me, not use case for unit tests. `local-result-dir` is the property responsible for local results.

If we want to verify it somehow we can spy on `BlobInfo` or `GcStorage` and check dir name correctness.

IMO, we should also check `results-dir` string if user is providing any illegal characters within. That would cause flank failure but later, after all tests run are finished (where it should fail fast if string is incorrect). I believe that was the original intention in #753 but shame on me because I did not provide detailed info. That resulted in wrong 'fix' -- that is causing problems like the one mentioned in description :)

**Comment by adamfilipow92** [comment]
@pawelpasterz I checked acceptable chars in 'results-dir' on GcStorage and it's accepting everything. 
Check this: [https://console.cloud.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq?prefix=result](url)

I was fix check in local storage on fill results-dir in this PR: https://github.com/Flank/flank/pull/785.
I think it's should be enought. 
Let me know it's what you think.

**Comment by bootstraponline** [comment]
> I don't think if this is something we can check easily (at least if we talk about unit tests). `results-dir` is a name for directory on gcs bucket. So to verify it we would need to connect to gcs and verify bucket which is, for me, not use case for unit tests. `local-result-dir` is the property responsible for local results.

You're right, I had confused `local-result-dir` with `result-dir` Let's not add a check for this.
