### ISSUE TITLE
Fladle - additional test apks

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#788]
https://github.com/runningcode/fladle/issues/96

**Comment by pawelpasterz** [comment]
Based on https://github.com/runningcode/fladle/issues/96#issuecomment-631176270 and https://github.com/Flank/flank/pull/801
I think we can close this issue since it was resolved.

**Comment by runningcode** [comment]
I am not sure what this issue is about :) I really appreciate your building of the ability to omit the debug apk and instrumentation apk and only specifying additional-app-test-apks. However, fladle will not be able to use this feature because many of the larger codebases with a large number of tests require more than 50 shards and also require the fulladle plugin to automatically configure the additional test apks. Thus in order to maintain backwards compatibility with flank 8.1.0 to support more than 50 shards, fladle will not use this new API for the time being.

**Comment by bootstraponline** [comment]
https://github.com/Flank/flank/issues/804 will enable bypassing the 50 shard limit once this is implemented.
