### ISSUE TITLE
Test results from shards with overlapping names in different matrices are lost

### ISSUE THREAD

**Issue by andrey-bolduzev** [Flank/flank#792]
_The below is a speculation based on the data I've been able to collect and interpret so far._

I'm trying to upgrade a fairly sized multi-module project to the latest flank version (via fladle) with minimal config changes but so far I'm unsuccessful at that, not sure if I'm doing something wrong.

The fladle plugin is applied to the top-level `build.gradle` and extra test apk's from the submodules are pulled in with `additionalTestApks`. After all the tests are run, we download sdcard contents of all shards from the returned combined test bucket. Specifically in our case, we are interested in `coverage.ec` files from all the sdcard, which we merge together with the help of the jacoco gradle plugin.

After upgrade to the new flank version, the coverage dropped suddenly and significantly. What I think is happening is files from different gradle modules are overwriting each other in the combined results bucket. So for instance for `:module1` 3 shards are created and collected in `Pixel2-29-en-portrait-shard_0/`, `Pixel2-29-en-portrait-shard_1/`, `Pixel2-29-en-portrait-shard_2/` directories in the combined bucket. Then say :module2 is large enough to have 2 shards created for its tests: `Pixel2-29-en-portrait-shard_0/`, `Pixel2-29-en-portrait-shard_1/`. All the directories with the overlapping names get copied over to the same bucket and the last one wins, so the coverage execution data from the "losing" shards is lost. There's also a new `Pixel2-29-en-portrait-test_results_merged.xml` file in the results bucket, which also doesn't contain all tests being run which confirms my suspicion that there are multiple `Pixel2-29-en-portrait-test_results_merged.xml` files coming from different matrices and this is just one survivor of them.

**Comment by pawelpasterz** [comment]
@bootstraponline 
I think we need to change a bit dirs structure in both gcs and locally. Right now we have (gcs) `/bucket/results-dir/devicename+shard+rerun` and locally `/local-result-dir/shard+rerun/devicename/files`. Problem is when we use `additional-test-app-apks` we basically tell FTL to put all results to the same directory. As result we end up with overwritten results of last finished matrix. My proposal is to add matrix level. gcs: `/bucket/results-dir/matrix-[index]/devicename(....)` , locally: `/local-result-dir/matrix-[index]/shard+rerun(...)`. index is every next number. Unfortunately we are unable to passs exact matrixId (ex `matrix-ygu4hybrbirda`) , this ID is available after matrices are launched (but we need to pass full `gcsPath` prior to that). Of course it does not need to be `matrix-[index]` , just my proposal. But definitely we need additional level

**Comment by jan-gogo** [comment]
@Pasterzp I agree, we need to separate results of different matrices runs to prevent overlapping. Proposal looks fine. I am wondering if this additional level should be added only with additionalTestApks.

**Comment by pawelpasterz** [comment]
> I agree, we need to separate results of different matrices runs to prevent overlapping. Proposal looks fine. I am wondering if this additional level should be added only with additionalTestApks.

IMO this should be for all cases

**Comment by bootstraponline** [comment]
> We can also think about reflecting gcs dir structure to local dir structure.

I like this idea. I think we should match gcs dir structure as much as possible so that it's easier for us to update in the future.

I have some notes from today when I reviewed the cloud gcs dir structure.
----

It looks like they create a base folder similar to Flank. The Flank folder creation is a port from gcloud.

- https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-19_21:42:55.400124_HWdz/


```
gcloud:
  num-flaky-test-attempts: 2
  app: ../test_app/apks/app-debug.apk
  test: ../test_app/apks/flaky-androidTest.apk
  num-uniform-shards: 2

flank:
  additional-app-test-apks:
   - test: ../test_app/apks/flaky-androidTest.apk
```

Example 1:

- walleye-26-en-portrait-rerun_1
- walleye-26-en-portrait-rerun_2 
- walleye-26-en-portrait-test_results_merged.xml 
- walleye-26-en-portrait

Example 2:

- walleye-26-en-portrait-shard_0-rerun_1/
- walleye-26-en-portrait-shard_0-rerun_2/ 
-  walleye-26-en-portrait-shard_0/
- walleye-26-en-portrait-shard_1-rerun_1/ 
- walleye-26-en-portrait-shard_1-rerun_2/
- walleye-26-en-portrait-shard_1/


Flank:
![image](https://user-images.githubusercontent.com/1173057/82406735-41af7100-9a1c-11ea-807d-816d97d4f7bb.png)

**Comment by bootstraponline** [comment]
> . Of course it does not need to be matrix-[index] , just my proposal. But definitely we need additional level.

I think `matrix_index` makes sense as well. This matches the shard_index and rerun_index format.

**Comment by bootstraponline** [comment]
we should probably remove `local-result-dir` in Flank, I'm not sure this feature adds value. I added this back when FTL had a much simpler execution model.

**Comment by pawelpasterz** [comment]
@bootstraponline do you have any knowledge if this change would break (or be non trivial to fix) CI's of some companies? I know it's essential to have this fixed but I am wondering if we should explicitly announce this change (cc @runningcode )

How about iOS? Current dir structure works fine, should we also change it? (IMO there will be no benefit from this right now since FTL does not support server side sharding for iOS)

> we should probably remove local-result-dir in Flank, I'm not sure this feature adds value. I added this back when FTL had a much simpler execution model.

Hm...not sure about it, I think some users might have benefit from this. I know that some companies uses result file as input to some unit tests plugins/tools. So custom directory for results would be beneficial (should we ask community about it?)

**Comment by bootstraponline** [comment]
> How about iOS? Current dir structure works fine, should we also change it? (IMO there will be no benefit from this right now since FTL does not support server side sharding for iOS)

The vision of Firebase Test Lab is to standardize testing across iOS and Android. I expect iOS sharding will be coming soon. For Flank, when it's possible to have the same experience across both platforms then I think that makes sense.

> do you have any knowledge if this change would break (or be non trivial to fix) CI's of some companies? I know it's essential to have this fixed but I am wondering if we should explicitly announce this change

I will take responsibility for breaking the CI. We can ask for feedback on the Slack channel. Flank is not currently instrumented https://github.com/Flank/flank/issues/748 so we have no current way of measuring the blast radius of changes like this. Slack is typically the best way to get feedback.

> I think some users might have benefit from this.

That's certainly possible. This goes back to https://github.com/Flank/flank/issues/748 I am not sure what features are used. I know this feature is not offered by gcloud. We can ask in Slack and see if anyone uses it. My guess is they could achieve a similar result with a `mv` command. If there are a bunch of users with this feature enabled though that would be interesting to know.

**Comment by pawelpasterz** [comment]
> The vision of Firebase Test Lab is to standardize testing across iOS and Android. I expect iOS sharding will be coming soon. For Flank, when it's possible to have the same experience across both platforms then I think that makes sense.

Ok, so I'll prepare the same implementation for iOS. When FTL will introduce server side sharding for android we will be already prepared :)
