### ISSUE TITLE
Flank should reflect gcloud exit codes

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#802]
Currently flank's exit codes are a bit different then gcloud's. Should flank's exit codes be the same?
[gcloud exit codes](https://firebase.google.com/docs/test-lab/android/command-line#script_exit_codes)
[flank exit codes](https://github.com/Flank/flank#exit-codes)

I'll create separate issue with detailed info if we come to conclusion.

**Comment by pawelpasterz** [comment]
@bootstraponline @jan-gogo @adamfilipow92 @piotradamczyk5 
WDYT?

**Comment by bootstraponline** [comment]
I think so! 🙂 

The vision I have for Flank is we are the same as gcloud plus a few more features.

**Comment by adamfilipow92** [comment]
Great Idea! 🙂

**Comment by jan-gogo** [comment]
Looks like, we have already implemented status codes `0` and `2` properly.

Exit code | Gcloud | Flank
-- | -- | --
0 | All test executions passed. | All tests passed
1 | A general failure occurred. Possible causes include: a filename that does not exist or an HTTP/network error. | All matrices finished but at least one test failed or inconclusive.
2 | Testing exited because unknown commands or arguments were provided. | Usually indicates missing or wrong usage of flags, incorrect parameters, errors in config files.
3 | | At least one matrix not finished (usually a FTL internal error) or unexpected error occurred.
10 | One or more test cases (tested classes or class methods) within a test execution did not pass.
15 | Firebase Test Lab could not determine if the test matrix passed or failed, because of an unexpected error.
18 | The test environment for this test execution is not supported because of incompatible test dimensions. This error might occur if the selected Android API level is not supported by the selected device type.
19 | The test matrix was canceled by the user.
20 | A test infrastructure error occurred.
