### ISSUE TITLE
Fix version printing on Flank release

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#951]
https://github.com/Flank/flank/releases/tag/v20.08.0 is not printing the correct version. We need to update the release scripts to include the correct version.

> version: local_snapshot

https://firebase-community.slack.com/archives/C72V6UW8M/p1596753876054200

**Comment by piotradamczyk5** [comment]
This is, because of using old `BITRISE_IO` variable name, should be changed to `CI` ([documentation](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables)) in [build.gradle.kts](https://github.com/Flank/flank/blob/master/test_runner/build.gradle.kts)

NOW:
`val runningOnBitrise get() = System.getenv("BITRISE_IO") != null`

SHOULD BE:
`val runningOnCI get() = System.getenv("CI") != null`
