### ISSUE TITLE
Gradle bintrayUpload does not work

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#953]
**Describe the bug**

Uploading flank using gradle plugin (bintrayUpload command) stop working with no reason, only for flank-snapshots( after each merge to master)

```
> Task :bintrayUpload FAILED
> Task :bintrayPublish
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/flank/maven/flank/flank_snapshot/com/github/flank/flank/flank_snapshot/flank-flank_snapshot.pom': HTTP/1.1 405 Not Allowed 405 Not Allowed405 Not Allowednginx
```

Version of snapshot is uploaded correctly, however when we upload .pom file there is an issue which breaks our CI

**To Reproduce**
> Steps to reproduce the behavior:

1. Push something to master and observer RELEASE CI job
2. See error

**Expected behavior**
> A clear and concise description of what you expected to happen.

`bintrayUpload` command should work properly for each file and should not fail the job.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

**Additional context**
> Add any other context about the problem here.

If there will be problem fixing this try:
- jfrog cli tool
- ask @bootstraponline  to create support ticket
- moving to GitHub packages

**Comment by Sloox** [comment]
There are many different reports of this exact issue occurring across the internet after a small investigation:
https://github.com/KrailOrg/krail-i18n/issues/4
https://devhub.vr.rwth-aachen.de/VR-Group/conan/conduit/-/jobs/26934
https://stackoom.com/question/262qP/Bintray-%E4%B8%8D%E5%85%81%E8%AE%B8Nginx

All of the resolutions were simply to wait as Bintray was having issues and they resolved themselves after some time.

I think that we should give it a day or two and come back and see if it resolves itself. Especially since the code has not been changed recently as confirmed by @piotradamczyk5 and it "suddenly" stopped working.

Else we could open a ticket for bintray as @bootstraponline suggested or simply upload elsewhere.

WDYGT?

**Comment by piotradamczyk5** [comment]
I tried to upload the pom file using `curl`:
```
curl -T <path to pom> -u<jfroguser>:<apikey> https://api.bintray.com/content/flank/maven/flank/flank_snapshot/com/github/flank/flank/flank_snapshot/flank-flank_snapshot.pom
```

and got
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by bootstraponline** [comment]
Thanks for the detailed investigation!

I'd like to try uploading to GitHub packages and see if that's a more stable option.

**Comment by piotradamczyk5** [comment]
Issue fixed by manual upload by web interface and sync with maven central
